# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

inhibit_all_warnings!

target 'FireNote' do
  use_frameworks!

  # Pods for FireNote

  # Codebase
  pod 'SwiftLint', '~> 0.38'
  pod 'SwiftFormat/CLI', '~> 0.43'
  pod 'R.swift'

  # UI
  pod 'Reusable'
  pod 'Cartography'
  pod 'Kingfisher'
  pod 'TPKeyboardAvoiding'
  pod 'WordPress-Aztec-iOS'
  pod 'KeyboardNotificationsObserver'

  # Storage
  pod 'SwiftKeychainWrapper'

  # Networking
  pod 'Moya'

  # Google Maps
  pod 'GoogleMaps'
  pod 'GooglePlaces'

  # Firebase
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Google'
  pod 'Firebase/Analytics'

  target 'FireNoteTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
