# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

inhibit_all_warnings!

target 'FireNote' do
  use_frameworks!

  # Pods for FireNote
  pod 'Firebase/Analytics'

  pod 'SwiftLint', '~> 0.38'
  pod 'SwiftFormat/CLI', '~> 0.43'

  pod 'Reusable'
  pod 'Cartography'
  pod 'Kingfisher'
  pod 'TPKeyboardAvoiding'
  pod 'SwiftKeychainWrapper'
  pod 'R.swift'
  pod 'WordPress-Aztec-iOS'
  pod 'KeyboardNotificationsObserver'

  # Firebase authentication
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Google'

  target 'FireNoteTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
